### ISSUE TITLE
Set number of lines to retrieve

### ISSUE THREAD

**Issue by Diego-Schmidt** [brightplum/nodejs-notebook#1]
Hello, thanks for this great module, I'm using it on a whatsappweb.js bot to store notes and it works great. Is there any way to set the line limit to retrieve? for example, there are like 40 lines of notes in the txt and i wish to retrieve just the last 7. Thanks again in advance.

**Comment by gmitch215** [comment]
Hello,
You should be able to retrieve the last 7 through Nodebook.fetchLine() with the size in Nodebook.lines().
Example:

```javascript
// nodebook as your notebook variable
var array = [];

for (let i = 0; i < 7; i++) {
  array.push(nodebook.fetchLine(nodebook.lines('utf-8' /* or any other encoding you want*/).length - i));
}

// more stuff...
```

 If this isn't what you are asking, are you referring to limiting the number of files able to be retrieved through the method?

**Comment by gmitch215** [comment]
Closed due to inactivity
